version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Create the "output" directory
          command: mkdir output
      - run:
          name: Copy a static local environment from the template directory
          command: cp environments/local-postman-environment.json postman-environment.json
      - run:
          name: Run Postman Tests
          command: (npm start > output/express.log &) && ./run-newman.sh
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: output